orders/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views as shop
from users import views as users
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'orders'

urlpatterns = [
    path('create_order/', views.create_order, name="create_order"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
['Nothing', 'will', 'work', 'unless', 'you', 'do']

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views as shop
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.main, name="index"),
    path('contacts/', views.contacts, name="contacts"),
    path('about/', views.about, name="about"),
    path('./catalog/1', views.catalog, name="catalog_1"),
    path('catalog/<int:page>/', views.catalog, name="catalog"),
    path('catalog/<int:page>/aboutplant/<int:plant_id>/',
         views.about_plant, name='aboutplant'),
    path('category/<int:choice>/<int:page>',
         views.category, name="category_id_page"),
    path('category/<int:choice>/1', views.category, name="category_id"),
    path('category/<int:choice>/<int:page>',
         views.category, name="category_id_page"),
    path('category/<int:page>/aboutplant/<int:plant_id>/',
         views.about_plant, name='aboutplant'),
    path('basket', views.basket, name="basket"),
    path('baskets/add/<int:plant_id>/', views.basket_add, name="basket_add"),
    path('catalog/<int:page>/aboutplant/<int:plant_id>/',
         views.basket_add, name="basket_add"),
    path('baskets/remove/<int:basket_id>/',
         views.basket_remove, name="basket_remove"),
    path('baskets/change_qty/<int:basket_id>/<slug:sign>/',
         views.basket_change_qty, name="basket_change_qty"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']

users/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views as shop
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
['Nothing', 'will', 'work', 'unless', 'you', 'do']

shop/models.py
from django.db import models
from users.models import User


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name="Категория")

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Plant(models.Model):
    name = models.CharField(max_length=50, verbose_name="Растение")
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, verbose_name="Категория")
    description = models.TextField(verbose_name="Описание", blank=True)
    image = models.ImageField(null=True, blank=True,
                              verbose_name="Фото", upload_to="media")
    available_quantity = models.IntegerField()
    price = models.FloatField(blank=True, verbose_name="Стоимость")
    height = models.CharField(blank=True, max_length=50, verbose_name="Высота")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['category', 'name']
        verbose_name = "Товар"
        verbose_name_plural = "Товары"


class BasketQuerySet(models.QuerySet):
    def total_qty(self):
        return sum(basket.quantity for basket in self)

    def quantity_in_basket(self):
        return {basket.plant.id: basket.quantity for basket in self}


class Basket(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="Пользователь")
    plant = models.ForeignKey(
        Plant, on_delete=models.CASCADE, verbose_name="Растение")
    quantity = models.PositiveSmallIntegerField(
        default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания")

    objects = BasketQuerySet.as_manager()

    class Meta:
        verbose_name = "Корзина"
        verbose_name_plural = "Корзины"

    def __str__(self):
        return f" Корзина для {self.user.username} Продукт: {self.plant.name}"

    def sum(self):
        return self.plant.price * self.quantity


['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']

shop/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from .models import *
from users.models import *
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib import auth, messages


def main(request):
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
        context = {'basket': basket, }
        return render(request, "shop/index.html", context)
    else:
        return render(request, "shop/index.html")


def contacts(request):
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
        context = {'basket': basket, }
        return render(request, "shop/contacts.html", context)
    else:
        return render(request, "shop/contacts.html")


def about(request):
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
        context = {'basket': basket, }
        return render(request, "shop/about.html", context)
    else:
        return render(request, "shop/about.html")


def catalog(request, page=1):
    search_query = request.GET.get('search', '')
    plants = Plant.objects.filter(
        Q(name__icontains=search_query.title()) | Q(name__icontains=search_query)) if search_query else Plant.objects.all()

    categories = Category.objects.all()

    paginator = Paginator(plants, 4)
    items_paginator = paginator.get_page(page)
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
        return render(request, "shop/catalog.html", {"plants": items_paginator, "categories": categories, "basket": basket, })
    else:
        return render(request, "shop/catalog.html", {"plants": items_paginator, "categories": categories, })


def category(request, choice, page=1):
    categories = Category.objects.all()
    selected_category = Category.objects.get(id=choice)

    search_query = request.GET.get('search', '')
    plants = Plant.objects.filter(Q(category=selected_category) & Q(name__icontains=search_query.title()) | Q(
        name__icontains=search_query)) if search_query else Plant.objects.all().filter(category=selected_category)

    paginator = Paginator(plants, 4)
    items_paginator = paginator.get_page(page)

    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
        return render(request, "shop/category.html", {'selected_category': selected_category, 'plants': items_paginator, "categories": categories, 'basket': basket, })
    else:
        return render(request, "shop/category.html", {'selected_category': selected_category, 'plants': items_paginator, "categories": categories, })


def about_plant(request, plant_id, page=1):
    selected_plant = Plant.objects.all().filter(pk=plant_id)

    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
        plant = Plant.objects.get(id=plant_id)
        return render(request, "shop/about_plant.html", {'selected_plant': selected_plant, 'basket': basket, 'plant': plant})
    else:

        return render(request, "shop/about_plant.html", {'selected_plant': selected_plant, })


@login_required
def basket(request):

    basket = Basket.objects.filter(user=request.user)
    context = {'basket': basket,
               'plant': Plant.objects.all(),
               'total_sum': "{:.2f}".format(sum(basket.sum() for basket in basket)),
               }

    return render(request, 'shop/basket.html', context)


@login_required
def basket_add(request, plant_id):
    plant = Plant.objects.get(id=plant_id)
    basket = Basket.objects.filter(user=request.user, plant=plant)

    if not basket.exists():
        Basket.objects.create(user=request.user, plant=plant,
                              quantity=1)

    else:
        basket = basket.first()
        if basket.quantity < basket.plant.available_quantity:
            basket.quantity += 1
            basket.save()
        else:
            messages.info(
                request, "Товар на складе закончился!")

    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':

        basket = Basket.objects.filter(user=request.user)

        data = {
            'message': plant.available_quantity,
            'message1': sum([qnt.quantity for qnt in basket]),
            'message2': basket.quantity_in_basket(),
        }

        return JsonResponse(data)

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_change_qty(request, basket_id, sign):

    basket = Basket.objects.get(id=basket_id)

    if sign == "plus":
        if basket.quantity < basket.plant.available_quantity:
            basket.quantity += 1
            basket.save()
        else:
            messages.info(
                request, "Товар на складе закончился!")

    else:
        if basket.quantity == 1:
            basket.delete()
        else:
            basket.quantity -= 1
            basket.save()

    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        baskets = Basket.objects.filter(user=request.user)

        data = {
            'a_basket_id': basket_id,
            'message': sum(basket.quantity for basket in baskets),
            'message1': basket.quantity,
        }

        return JsonResponse(data)

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']

templates/shop/about_plant.html
{% extends "main.html"%}

{% load static %}

{% block title %}About plant{% endblock title %}

{% block content %}
{% comment %} <div class="info_message_for_the_buyer">
    {% if messages %}
    {% for message in messages %}
    {{message}}
    {% endfor %}
    {% endif %}
</div>  {% endcomment %}

 
<table class="aboutplant_table">
    {%for selected_plant in selected_plant%}

<tr><td class="image_td" rowspan="5"> <img class="aboutplant_img" src={{selected_plant.image.url}}></td><td class="aboutplant_name" >{{selected_plant.name}}</td></tr>

<tr><td class="aboutplant_price">{{selected_plant.price}} р.</td></tr>

<tr><td class="aboutplant_height">{{selected_plant.height}} </td></tr>

<tr><td>
    <div class="in_basket_about_plant">
    <form id="form_buying_plant" {% if request.user.is_authenticated %} 
    data-plant_id = "{{plant.id}}" 
    data-basket_total_qty="{{basket.total_qty}}"
    data-qty_in_basket="{{basket.quantity_in_basket}}"
    data-available_quantity="{{plant.available_quantity}}"
    action="{% url 'shop:basket_add' plant.id %}"
    {% else %} 
    action="{% url 'users:login'%}"
    {% endif %}>
        {% csrf_token %}
        {% if request.user.is_authenticated %}
                    {% if plant.available_quantity %}
                <button  type="submit" id="submit_btn" class="about_plant_in_basket" >
                В корзину    
                </button>
                    {% elif plant.available_quantity == 0  %}
                    <button  type="submit" id="submit_btn" class="in_busket_a disabled_button" disabled>
                    В корзину    
                    </button>
                {% endif %}
    {% else %}
    <button  type="submit" id="submit_btn" class="in_basket_about_plant_btn" >
        <a class="in_busket_a" href="{% url "users:login" %}">В корзину </a>    
    </button>
{% endif %}




    </form>
</div>
     </td></tr>
<tr><td class="aboutplant_description">{{selected_plant.description}} </td></tr>
    
</table>   
    
{% endfor %}

{% endblock%}

templates/shop/basket.html
{% extends "main.html" %}
{% load static %}


{% block content %}

<div class="bg_basket">
    <img class=""src="{%static "images/bg_basket.png"%}" alt="">
</div>
<div class="info_message_for_the_buyer">
    {% if messages %}
    {% for message in messages %}
    {{message}}
    {% endfor %}
    {% endif %}
</div>
<div class="basket">
    {% if basket%}
            <table class="basket_in_order">
                <thead>
                <tr><th>Товар</th><th>Количество</th><th>Изменить количество</th><th>Стоимость</th></tr>
                </thead>
                <tfoot>
                    <tr><th colspan="3" class="order_total_sum ">Итоговая стоимость: </th><th>{{total_sum}} </th></tr>
                </tfoot>
                <tbody>
                    {% for basket in basket %}
                <tr><td>{{basket.plant.name}}</td>
                    <td id = "{{basket.id}}" >{{basket.quantity}}</td>
                    <td>

                        <a id = "oneminus" data-basket_id ="{{basket.id}}" data-sign="minus" data-basket_quantity="{{basket.quantity}}"   class = "basket_img_a" href="{%url 'shop:basket_change_qty' basket_id=basket.id sign='minus' %}">
                        <img  class = "basket_quantity_change" src= "{% static "images/oneminus.png" %}">
                        </a>
                        <a id = "oneplus" class = "basket_img_a" href="{%url 'shop:basket_change_qty' basket_id=basket.id sign='plus' %}"> 
                        <img class = "basket_quantity_change" src= "{% static "images/oneplus.png" %}">
                        </a>
                        <a id = "del_from_basket" data-basket_plant_id ="{{basket.plant.id}}" class = "basket_img_a" href="{%url 'shop:basket_remove' basket.id%}">
                        <img class = "basket_quantity_delete" src= "{% static "images/delete.png" %}">
                        </a>
                    </td>
                    <td>{{basket.sum}}</td></tr>   
                    {% endfor %}
                </tbody>
            </table>

        <div class ="basket_add_order_div">Создать заказ:
            <a class ="basket_add_order" href="{% url "orders:create_order" %}" >
            <img class = "basket_add_order_img" src= "{% static "images/order.png" %}">
            </a>
        </div>


    {% else %}
    <div class="basket_message">
        Корзина пуста
    </div>

    {% endif %}

</div>

{% endblock  %}

templates/shop/catalog.html
{% extends "main.html" %}

{% load static %}
{% block title %}Catalog{% endblock %}


{% block content %}

<div class="search">
    <form action="{% url "shop:catalog_1" %}">
    <input type="search" placeholder = "Введите назнание..." name="search">
    <button class="search_btn">
        Поиск
    </button> 
    
</form>
</div>

<div class="filter">
    <form >
        <select name='select'>
        <option selected value="/catalog/1/">Вce категории</option>
        {% for cat in categories  %}
          <option  value="/category/{{cat.id}}/1">{{cat.name}}</option>
          {% endfor %}
          </select>
        <input class="select" type = button value="Перейти"  onclick='top.location.href=this.form. select.options[this.form.select.selectedIndex].value' />
    </form>
</div>
 {% comment %} <div class="info_message_for_the_buyer">
    {% if messages %}
    {% for message in messages %}
    {{message}}
    {% endfor %}
    {% endif %}
</div>  {% endcomment %}

<div class="catalog_div">
    {% for plant in plants %}
    <div class="item_card"> 
        <div class="item_img">
            <img class="item_img" src={{plant.image.url}}>
        </div>
        <div class="item_name">
            <h3> <a class="aboutplant" href="aboutplant/{{plant.id}}">{{plant.name}}</a></h3>
        </div>
        
        <div class="item_height">
            <h4>Высота: {{plant.height}}</h4>
        </div>
        <div class="item_price">
            <h4>{{plant.price}} р.</h4>
        </div>

        <div class="in_basket">
            
            <form id="form_buying_plant" {% if user.is_authenticated%} data-plant_id = "{{plant.id}}" data-basket_total_qty="{{basket.total_qty}}" data-qty_in_basket="{{basket.quantity_in_basket}}" data-available_quantity="{{plant.available_quantity}}" action="{% url 'shop:basket_add' plant.id %}" {% else %} action="{% url 'shop:basket_add' plant.id %}" {% endif %} >
                {% csrf_token %}
                {% if request.user.is_authenticated %}
                    {% if plant.available_quantity %}
                <button  type="submit" id="submit_btn" class="in_busket_a" >
                В корзину    
                </button>
                    {% elif plant.available_quantity == 0  %}
                    <button  type="submit" id="submit_btn" class="in_busket_a disabled_button" disabled>
                    В корзину    
                    </button>
                {% endif %}
            {% else %}
            <button  type="submit" id="submit_btn" >
                <a class="in_busket_a" href="{% url "users:login" %}">В корзину </a>    
                </button>
            
        {% endif %}
            </form>

        </div>

    </div>
    {% endfor %}
</div>
    
    <nav class="my_pagination">
        <ul class="pagination ">

        <li class="page-item">
            {% if plants.has_previous %}
            <a class="page-link " href=" {% url 'shop:catalog' page=plants.previous_page_number %} ">Предыдущая</a>
            {% endif %}
        </li>

        {% for num_page in plants.paginator.get_elided_page_range %}
        {% if  num_page == plants.number%}
        <li class="current_page-item" >
            <a class="page-link " href=" {% url "shop:catalog" page=num_page  %} ">{{plants.number}}</a>
        </li>

        {% endif %}
        {% endfor %}


        {% if plants.has_next %}
        <li class="page-item">
            <a class="page-link" href="{% url 'shop:catalog' page=plants.next_page_number %}">Следующая</a>
        </li>
        {% endif %}   
        </ul>
    </nav>


{% endblock content %}

templates/shop/category.html
{% extends "main.html" %}

{% load static %}
{% block title %}Category{% endblock %}

{% block content %}
<div class="search">
    <form action="{% url "shop:catalog_1" %}">
    <input type="search" placeholder = "Введите назнание..." name="search">
    <button class="search_btn">
        Поиск
    </button>
</form>
</div>
<div class="filter">
    <form >
        <select name='select'>
        <option selected value="/catalog/1/">Вce категории</option>
        {% for cat in categories  %}
          <option  value="/category/{{cat.id}}/1">{{cat.name}}</option>
          {% endfor %}
          </select>
        <input class="select" type = button value="Перейти"  onclick='top.location.href=this.form. select.options[this.form.select.selectedIndex].value' />
    </form>
</div>
<div class="catalog">
    {% for plant in plants %}
    <div class="item_card"> 
        <div class="item_img">
            <img class="item_img" src={{plant.image.url}}>
        </div>
        <div class="item_name">
           <h3> <a class="aboutplant" href="aboutplant/{{plant.id}}">{{plant.name}}</a></h3>
        </div>
        
        <div class="item_height">
            <h4>Высота: {{plant.height}}</h4>
        </div>
        <div class="item_price">
            <h4>{{plant.price}} р.</h4>
        </div>
        <div class="in_basket">
            
            <form id="form_buying_plant" {% if request.user.is_authenticated %} data-plant_id = "{{plant.id}}" data-basket_total_qty="{{basket.total_qty}}" data-qty_in_basket="{{basket.quantity_in_basket}}" data-available_quantity="{{plant.available_quantity}}" action="{% url 'shop:basket_add' plant.id %}" {% else %} action="{% url 'shop:basket_add' plant.id %}" {% endif %} >
                {% csrf_token %}
                
                {% if request.user.is_authenticated %}
                    {% if plant.available_quantity %}
                <button  type="submit" id="submit_btn" class="in_busket_a" >
                В корзину    
                </button>
                    {% elif plant.available_quantity == 0  %}
                    <button  type="submit" id="submit_btn" class="in_busket_a disabled_button" disabled>
                    В корзину    
                    </button>
                {% endif %}
                    {% else %}
                    <button  type="submit" id="submit_btn" >
                        <a class="in_busket_a" href="{% url "users:login" %}">В корзину </a>    
                        </button>
                    
                {% endif %}
            
            </form>

        </div>

    </div>
    {% endfor %}
</div>


<nav class="my_pagination">
    <ul class="pagination ">

    <li class="page-item">
        {% if plants.has_previous %}
        <a class="page-link " href=" {% url "shop:category_id_page" choice=selected_category.id page=plants.previous_page_number %} ">Предыдущая</a>
        {% endif %}

        
    </li>
    {% for num_page in plants.paginator.get_elided_page_range %}
    {% if  num_page == plants.number%}
    <li class="current_page-item" >
        <a class="page-link " href=" {% url "shop:category_id_page" choice=selected_category.id page=num_page %} ">{{plants.number}}</a>
    </li>
    {% endif %}
    {% endfor %}


    {% if plants.has_next %}
    <li class="page-item">
        <a class="page-link" href="{% url "shop:category_id_page" choice=selected_category.id page=plants.next_page_number %}">Следующая</a>
    </li>
    {% endif %}   
    </ul>
</nav>



{% endblock content %}

templates/shop/footer.html
{%load static%}

    <div class="footer">
        <div class='conteiner_footer grid-container'>
            <ul class="grid-element">Контакты
                <!-- <li> Контакты</li> -->
                <li></li>
                <li class="contact_img">
                    <img src="{% static "images/whatsapp.png"%}" >
                    <img src="{% static "images/instagram.png"%}" >
                    <img src="{% static "images/telegram.png"%}" >
                    <img src="{% static "images/vk.png"%}" >
                </li>
                <li> +375 29 391 38 72 </li>
                <li> bonsai@mail.ru</li>
            </ul>


            <ul class="grid-element">
                <li class="confidentiality">Политика конфиденциальности </li>
                <li class="contractoffer">Договор публичной оферты </li>
                <li class="payment"><img class="payment" src="{% static "images/payment.png"%}"></li>
            </ul>


            <ul class="grid-element">Режим работы

                <li> </li>
                <li> С 10.00 до 20.00</li>
                <li>Ежедневно, без выходных</li>
                <li>г.Минск пр-т Жукова д.47</li>
            </ul>


        </div>
    </div>

templates/shop/header.html
{%load static%}

    <div class="header">

        <div class="logo">
            <a class="logo" href="{% url "shop:index"%}">
            <img class="logo" src="{% static "images/bonsailogo.png"%}">
            </a>
        </div>

        <div class="buttons">
            
            {% if user.is_authenticated%}

            <div class='user_profile'>
                <a href="{% url "users:profile" %}"> <img class='user_profile_img' src="{% static "users_images/userprofile.png" %}"> </a>
            </div>

            <div class="profile_busket">
                <a href="{% url "shop:basket"%}"> <img src="{% static "images/busket.png" %}"></a>
                
            </div>
            <div class="total_qty" id="total_qty" data-basket_total_qty = "{{basket.total_qty}}" >
                {{basket.total_qty}}
            </div>

            <div class="logout">
                <a href="{% url "users:logout" %}">Выход</a>
            </div>

            {%else%}

            <div class="login">
                <a href="{% url "users:login" %}">Войти</a>
            </div>


            {%endif%}
        </div>

    </div>

templates/shop/included_basket.html
{% load static %}
<div class="included_basket">
    {% if basket%}
            <table class="basket_in_order">
                <thead>
                <tr><th>Товар</th><th>Количество</th><th>Изменить количество</th><th>Стоимость</th></tr>
                </thead>
                <tfoot>
                    <tr><th colspan="3" class="order_total_sum ">Итоговая стоимость: </th><th>{{total_sum}} </th></tr>
                </tfoot>
                <tbody>
                    {% for basket in basket %}
                <tr><td>{{basket.plant.name}}</td>
                    <td>{{basket.quantity}}</td>
                    <td>
                        <a class = "basket_img_a" href="{%url 'shop:basket_change_qty' basket_id=basket.id sign='minus' %}">
                        <img class = "basket_quantity_change" src= "{% static "images/oneminus.png" %}">
                        </a>
                        <a class = "basket_img_a" href="{%url 'shop:basket_change_qty' basket_id=basket.id sign='plus' %}"> 
                        <img class = "basket_quantity_change" src= "{% static "images/oneplus.png" %}">
                        </a>
                        <a class = "basket_img_a" href="{%url 'shop:basket_remove' basket.id%}">
                        <img class = "basket_quantity_delete" src= "{% static "images/delete.png" %}">
                        </a>
                    </td>
                    <td>{{basket.sum}}</td></tr>   
                    {% endfor %}
                </tbody>
            </table>

        <div class ="basket_add_order_div">Создать заказ:
            <a class ="basket_add_order" href="{% url "orders:create_order" %}" >
            <img class = "basket_add_order_img" src= "{% static "images/order.png" %}">
            </a>
        </div>


    {% else %}
    {% if messages %}
    {% for message in messages %}
        <p class ="order_is_processed"{% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</p>
    {% endfor %}
    {% endif %}
    <div class="basket_message">
        Корзина пуста
    </div>

    {% endif %}

</div>

templates/shop/navbar.html
{%load static%}

<ul class="navbar">
    {%block navbar%}
    <li><a href="{% url "shop:index"%}">Главная</a></li>
    <li><a href="{% url "shop:about"%}">О нас</a></li>
    <li><a href="{% url "shop:catalog_1"%}">Каталог</a></li>
    <li><a href="{%url "shop:contacts"%}">Контакты</a></li>
    {%endblock navbar%}
</ul>