orders/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views as shop
from users import views as users
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'orders'

urlpatterns = [
    path('create_order/', views.create_order, name="create_order"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
['Nothing', 'will', 'work', 'unless', 'you', 'do']

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views as shop
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.main, name="index"),
    path('contacts/', views.contacts, name="contacts"),
    path('about/', views.about, name="about"),
    path('./catalog/1', views.catalog, name="catalog_1"),
    path('catalog/<int:page>/', views.catalog, name="catalog"),
    path('catalog/<int:page>/aboutplant/<int:plant_id>/',
         views.about_plant, name='aboutplant'),
    path('category/<int:choice>/<int:page>',
         views.category, name="category_id_page"),
    path('category/<int:choice>/1', views.category, name="category_id"),
    path('category/<int:choice>/<int:page>',
         views.category, name="category_id_page"),
    path('category/<int:page>/aboutplant/<int:plant_id>/',
         views.about_plant, name='aboutplant'),
    path('basket', views.basket, name="basket"),
    path('baskets/add/<int:plant_id>/', views.basket_add, name="basket_add"),
    path('catalog/<int:page>/aboutplant/<int:plant_id>/',
         views.basket_add, name="basket_add"),
    path('baskets/remove/<int:basket_id>/',
         views.basket_remove, name="basket_remove"),
    path('baskets/change_qty/<int:basket_id>/<slug:sign>/',
         views.basket_change_qty, name="basket_change_qty"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']

orders/models.py
from django.db import models

from users.models import User
from shop.models import *


class OrderitemQueryset(models.QuerySet):

    def total_price(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        if self:
            return sum(basket.quantity for basket in self)
        return 0


class Order(models.Model):

    status = (
        ("В обработке", "В обработке",),
        ("Оформлен", "Оформлен",),
        ("Собран", "Собран",),
        ("Доставлен", "Доставлен",),
        ("Закрыт", "Закрыт",),
    )

    user = models.ForeignKey(
        User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания заказа")
    email = models.CharField(
        max_length=20, verbose_name="Адрес эл почты")
    delivery_address = models.TextField(
        null=True, blank=True, verbose_name="Адрес доставки")
    payment_on_get = models.BooleanField(
        default=False, verbose_name="Оплата при получении")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(
        max_length=50, choices=status, default=status[0][0], verbose_name="Статус заказа")

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return f"Заказ №{self.pk}"


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, verbose_name="Заказ")
    plant = models.ForeignKey(Plant, on_delete=models.SET_DEFAULT,
                              null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(
        max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(
        default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата продажи")

    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round((self.plant.price) * self.quantity, 2)

    def __str__(self):
        return f"Товар {self.name} Заказ № {self.order.pk}"


['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']

orders/forms.py
from django import forms


class CreateOrderForm(forms.Form):

    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.CharField()
    requires_delivery = forms.ChoiceField(
        choices=[
            ("0", "False"),
            ("1", "True"),
        ],
    )
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(
        choices=[
            ("0", "False"),
            ("1", "True"),
        ],
    )
['Nothing', 'will', 'work', 'unless', 'you', 'do']

orders/views.py
from django.shortcuts import render, redirect
from .models import *
from users.models import *
from shop.models import *
from orders.forms import *
from django.db import transaction
from django.contrib import messages
from django.core.exceptions import ValidationError


def create_order(request):
    basket = Basket.objects.filter(user=request.user)
    print(basket)
    if request.method == 'POST':
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    baskets = Basket.objects.filter(user=request.user)
                    if basket.exists():
                        order = Order.objects.create(
                            user=user,
                            email=form.cleaned_data['email'],
                            delivery_address=form.cleaned_data['delivery_address'],
                            payment_on_get=form.cleaned_data['payment_on_get'],
                        )

                        for basket in baskets:
                            plant = basket.plant
                            name = basket.plant.name
                            price = basket.sum()
                            quantity = basket.quantity

                            if basket.plant.available_quantity < quantity:
                                raise ValidationError(
                                    f"Недостаточное количество товара {name} на складе, в наличии {basket.plant.available_quantity}")

                            OrderItem.objects.create(
                                order=order,
                                plant=plant,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )
                            plant.available_quantity -= quantity
                            plant.save()

                        baskets.delete()

                        messages.success(request, "Заказ оформлен!")
                        return redirect("users:profile")
            except VaidationError as e:
                messages.success(request, str(e))
                return redirect("orders:create_order")

    else:
        initial = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'email': request.user.email,
        }

        form = CreateOrderForm(initial=initial)

    context = {
        'form': form,
        'basket': basket,
        'total_sum': "{:.2f}".format(sum(basket.sum() for basket in basket)),
    }

    return render(request, "orders/create_order.html", context)
['Nothing', 'will', 'work', 'unless', 'you', 'do']

templates/orders/create_order.html
{% extends "main.html" %}
{% load static %}


{% block content %}
<div class="bg_basket">
    <img class=""src="{%static "images/bg_basket.png"%}" alt="">
</div>
<div class="info_message_for_the_buyer">
    {% if messages %}
    {% for message in messages %}
    {{message}}
    {% endfor %}
    {% endif %}
</div> 
<form action ="{% url "orders:create_order"%}" method="post">
    {% csrf_token %}
<div class="order_card">
<table class="basket_in_order">
    <thead>
    <tr><th>Товар</th><th>Количество</th><th>Изменить количество</th><th>Стоимость</th></tr>
    </thead>
    <tfoot>
        <tr><th colspan="3" class="order_total_sum ">Итоговая стоимость: </th><th>{{total_sum}} </th></tr>
    </tfoot>
    <tbody>
        {% for basket in basket %}
    <tr><td>{{basket.plant.name}}</td>
        <td>{{basket.quantity}}</td>
        <td>
            <a class = "basket_img_a" href="{%url 'shop:basket_change_qty' basket_id=basket.id sign='minus' %}">
            <img class = "basket_quantity_change" src= "{% static "images/oneminus.png" %}">
            </a>
            <a class = "basket_img_a" href="{%url 'shop:basket_change_qty' basket_id=basket.id sign='plus' %}"> 
            <img class = "basket_quantity_change" src= "{% static "images/oneplus.png" %}">
            </a>
            <a class = "basket_img_a" href="{%url 'shop:basket_remove' basket.id%}">
            <img class = "basket_quantity_delete" src= "{% static "images/delete.png" %}">
            </a></td>
            <td>{{basket.sum}}</td></tr>   
        {% endfor %}
    </tbody>
</table>


<table class="order_details">  
    <tr>
        <th class="th_first_name"><label for="id_first_name">Имя:</lable></th>
        <th class="th_last_name"><label for="id_last_name">Фамилия:</lable></th>
        <th class="th_email"><label for="id_email">Электронная почта:</lable></th>
    </tr>  
    <tr>
        <td class="td_first_name"><input type="text" class="form_control", id="id_first_name" name="first_name" value="{% if form.first_name.value %}{{form.first_name.value}}{% endif %}" required></td>
        <td class="td_last_name"><input type="text" class="form_control", id="id_last_name" name="last_name" value="{% if form.last_name.value %}{{form.last_name.value}}{% endif %}"  required></td>
        <td class="td_email"><input type="email" class="form_control", id="id_email" name="email" placeholder="В формате: ***@***.** " value="{% if form.email.value %}{{form.email.value}}{% endif %}"  required></td>
    </tr>  
</table>
<div class="delivery_method">
    <label for ="delivery" class="form_label">Способ доставки: </lable>

        <input type="radio" name="requires_delivery" id="id_requires_delivery" value="1" checked>
        <label for ="id_requires_delivery"> Нужна доставка </lable>

        <input type="radio" name="requires_delivery" id="id_requires_delivery" value="0" >
        <label for ="id_requires_delivery"> Самовывоз </lable>
</div>
<div class="delivery_address">
    <label for="id_delivery_address" class="form_label">Адрес доставки:</label>
    <textarea name="delivery_address" id="id_delivery_address"></textarea>
</div>
<div class="payment_method">
    <label for="" class="form_label">Способ оплаты:</label>
    <input type="radio" name="payment_on_get" id="id_payment_on_get" value="0" checked >
    <label for="id_payment_on_get">Оплата картой</label>

    <input type="radio" name="payment_on_get" id="id_payment_on_get" value="1" >
    <label for="id_payment_on_get">Наличными/картой при получении</label>
    {% if form.payment_on_get.errors %}
    <messages class="errors"></messages>
    {% endif %}

    <button class="create_order_btn">Оформить заказ</button>
</div>

</form>
</div>

{% endblock %}

templates/orders/included_orders.html
{% load static %}

{% if orders %}
<table class="order_details">
    <thead>
        <tr>
            <th>Номер заказа</th>
            <th>Дата заказа</th>
            <th>Способ оплаты</th>
            <th>Доставка</th>
            <th>Статус заказа</th>
        </tr>
    </thead>
    <tbody>
        {% for order in orders%}
        <tr>
           <td>{{order}}</td>
           <td>{{order.created_timestamp}}</td>
           <td>{% if order.payment_on_get %}
            Оплата при получении
            {% else %}
            Оплачен
            {% endif %}</td>
           <td>{% if order.delivery_address %}
            {{order.delivery_address}}
            {% else %}
            Самовывоз
            {% endif %}</td>
           <td>
            {{order.status}}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<div class="order_message">
    У Вас пока нет оформленных заказов
</div>

{% endif %}