shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views as shop
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.main, name="index"),
    path('contacts/', views.contacts, name="contacts"),
    path('about/', views.about, name="about"),
    path('./catalog/1', views.catalog, name="catalog_1"),
    path('catalog/<int:page>/', views.catalog, name="catalog"),
    path('catalog/<int:page>/aboutplant/<int:plant_id>/',
         views.about_plant, name='aboutplant'),
    path('category/<int:choice>/<int:page>',
         views.category, name="category_id_page"),
    path('category/<int:choice>/1', views.category, name="category_id"),
    path('category/<int:choice>/<int:page>',
         views.category, name="category_id_page"),
    path('category/<int:page>/aboutplant/<int:plant_id>/',
         views.about_plant, name='aboutplant'),
    path('basket', views.basket, name="basket"),
    path('baskets/add/<int:plant_id>/', views.basket_add, name="basket_add"),
    path('catalog/<int:page>/aboutplant/<int:plant_id>/',
         views.basket_add, name="basket_add"),
    path('baskets/remove/<int:basket_id>/',
         views.basket_remove, name="basket_remove"),
    path('baskets/change_qty/<int:basket_id>/<slug:sign>/',
         views.basket_change_qty, name="basket_change_qty"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']
['Nothing', 'will', 'work', 'unless', 'you', 'do']

users/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views as shop
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
['Nothing', 'will', 'work', 'unless', 'you', 'do']

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    photo = models.ImageField(upload_to='users_images',
                              null=True, blank=True, verbose_name="Аватар")
    phone_number = models.CharField(max_length=13, blank=True, null=True)

    class Meta:
        db_table = "user"
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username
['Nothing', 'will', 'work', 'unless', 'you', 'do']

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User
from django import forms


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'user_name_login', 'placeholder': 'Введите логин', 'name': 'user'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'pass', 'placeholder': 'Введите пароль', 'name': 'pass'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'user_name_registr', 'placeholder': 'Введите имя', 'name': 'user_name'}))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'user_surname', 'placeholder': 'Введите фамилию', 'name': 'user_surname'}))
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'user_name_registr', 'placeholder': 'Введите логин', 'name': 'user'}))
    email = forms.CharField(widget=forms.EmailInput(
        attrs={'class': 'user_email_registr', 'placeholder': 'Введите адрес эл. почты', 'name': 'email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'pass', 'placeholder': 'Введите пароль', 'name': 'password1'}))
    password2 = forms.CharField(initial="rt", widget=forms.PasswordInput(
        attrs={'class': 'pass', 'placeholder': 'Подтвердите пароль', 'name': 'password2'}))

    class Meta:
        model = User
        labels = {'password1': 'Введите пароль',
                  'password2': 'Повторите пароль', }
        fields = ('first_name', 'last_name', 'username',
                  'email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'user_name', 'name': 'user_name'}))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'user_surname', 'name': 'user_surname'}))
    photo = forms.ImageField(
        widget=forms.FileInput(attrs={'class': 'user_photo'}), required=False)
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'user', 'name': 'user', 'readonly': True}))
    email = forms.CharField(widget=forms.EmailInput(
        attrs={'class': 'user_email', 'name': 'email', 'readonly': True}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'photo', 'username', 'email')
['Nothing', 'will', 'work', 'unless', 'you', 'do']

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth, messages
from .models import *
from shop.models import *
from orders.models import *
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from django.contrib.auth.decorators import login_required


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('shop:catalog_1'))
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, "Вы успешно зарегистрированы!")
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/registration.html', context)


@login_required
def profile(request):
    if request.method == "POST":
        form = UserProfileForm(instance=request.user,
                               data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance=request.user)
        basket = Basket.objects.filter(user=request.user)
        orders = Order.objects.filter(user=request.user)

    context = {'form': form,
               'basket': basket,
               'plant': Plant.objects.all(),
               'total_sum': sum(basket.sum() for basket in basket),
               'orders': orders,
               }
    return render(request, 'users/profile.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('shop:index'))
['Nothing', 'will', 'work', 'unless', 'you', 'do']

templates/users/login.html
{% extends "main.html" %}

{% load static %}
{% block title %}Login{% endblock %}


{% block content %}
    <div class="users_background">
    <div class="users_wrapper alert {% if messages%} alert-success {%else%} alert-warning{%endif%}">
        {%if messages or form.non_field_errors%}
            {% if messages%}
                {% for message in messages%}
                    {{message}}
                {% endfor %}
            {%else%}
                {{form.non_field_errors}}
            {%endif%}
        {%endif%}
        <form class="signin" method="post" action="{% url "users:login" %}" autocomplete="off">
            {% csrf_token %}
            {{form.username}}
            {{form.password}}
            
            <button type="submit">&#xf0da;</button>
            <p>Еще нет аккаунта? <a href="{% url "users:registration" %}">Регистрация</a></p>
        </form>
    </div> 
</div> 

{% endblock %}

templates/users/profile.html
{% extends "main.html" %}
{% load static %}
{% block title %}User account{% endblock %}


{% block content %}
<div class="bg_profile">
    <img class=""src="{%static "images/bg_profile.png"%}" alt="">
</div>

<div class = 'user_profile_form'>
    <img class='user_profile_photo' src="{% if user.photo %}{{user.photo.url}}{%else%}{% static 'users_images/user_profile.png'%}{% endif %}">
<form  action=" {% url "users:profile"%} " method = "post" enctype="multipart/form-data" >
    {% csrf_token %}
    <div class='user_profile_photo'>
        <label class='user_profile_label' for ="{{ form.photo.id_for_label}}"> </label> 
    {{form.photo}}
    </div>
    <div class='user_profile_info'> 
        <label class='user_profile_label' for ="{{ form.first_name.id_for_label}}"> Имя </label> 
    {{form.first_name}}
        <label class='user_profile_label' for ="{{ form.last_name.id_for_label}}"> Фамилия </label> 
    {{form.last_name}}
    </div>
    <div class='user_profile_info_onlyreading'>
        <label class='user_profile_label' for ="{{ form.username.id_for_label}}"> Логин </label> 
    {{form.username}}
    <label class='user_profile_label' for ="{{ form.email.id_for_label}}"> Email </label> 
    {{form.email}}
    </div>
    <button type="submit"> Сохранить </button>
</form>

</div>


{% include "shop/included_basket.html" %}
{% include "orders/included_orders.html" %}




{% endblock%}

templates/users/registration.html
{% extends "main.html" %}

{% load static %}
{% block title %}Registration{% endblock %}

{% block content %}
    <div class="users_wrapper">
        <div class="form_errors">
        {%if form.errors%}
        {{form.errors}}
        {%endif%}
        </div>
        <form class="registration" method="post" action="{% url "users:registration" %}" autocomplete="off">
            {% csrf_token %}
            {{form.first_name}}
            {{form.last_name}}
            {{form.username}}
            {{form.email}}
            {{form.password1}}
            {{form.password2}}

            <button type="submit">Создать аккаунт</button>
            <p>Уже есть аккаунт? <a href="{% url "users:login" %}">Авторизоваться</a></p>
        </form>
    </div>  
{% endblock %}